"""empty message

Revision ID: 767d18fbf73b
Revises: 
Create Date: 2023-09-16 17:17:19.525099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767d18fbf73b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_username'))

    op.drop_table('USER')
    # ### end Alembic commands ###
